### ISSUE TITLE
standardize Helm Chart with Bitnami Practices 

### ISSUE THREAD

**Issue by migmartri** [chainloop-dev/chainloop#1151]
From [https://github.com/bitnami/charts/pull/27100#issuecomment-2256043379](https://github.com/bitnami/charts/pull/27100#issuecomment-2256043379)

NOTE: It's essential to evaluate and discuss each breaking change we might add to the chart.
```[tasklist]
### Tasks
- [x] Openshift settings
- [x] hardcoded ports in configmap/secrets
- [x] auto-scaling
- [x] network policies
- [ ] tls.existingSecret? https://github.com/bitnami/charts/pull/27100#discussion_r1705381329
- [x] fix hpa i.e  averageUtilization: {{ .Values.controlplane.autoscaling.hpa.targetMemory }}
- [x] hardcode container names "We usually hardcode a container name, in this case we could use 'controlplane'"
```

**Comment by migmartri** [comment]
So the chart has now been merged in Bitnami. Awesome! Great work @javirln!

I believe the last batch of feedback included some missing features in our chart that were applied in their branch, but not in ours. I think some of those changes should be merged also in our chart. @javirln do you have any suggestion on which ones should we add back?
