### ISSUE TITLE
feature: http download endpoint for  items in CAS

### ISSUE THREAD

**Issue by migmartri** [chainloop-dev/chainloop#293]
Currently, downloads are performed using the CLI (chainloop artifact download) which hits the `Read` RPC endpoint https://github.com/chainloop-dev/chainloop/blob/f6ec84dfc52b82515938ff1a3b51a4f2f32e3f50/app/artifact-cas/internal/service/bytestream.go#L127

This endpoint requires the `digest` of the artifact to download and an authentication with a short lived token with download permissions.

This task is about creating a similar endpoint but in an HTTP endpoint. i.e `download/sha256:deadbeef?t=short_lived_token` 

This will enable download links from notifications, webUIs and so on.

Note that this task is only about implementing the endpoint in the artifact-cas-proxy, not about an additional endpoint that we will need to do in the control-plane which will craft such download token for the user (that will be another task). 
```[tasklist]
### Tasks
- [ ] https://github.com/chainloop-dev/chainloop/pull/294
- [x] feat(deployment): enable http ingress in Helm Chart https://github.com/chainloop-dev/chainloop/pull/305
- [x] Enable new http CAS endpoint in Chainloop cloud
- [x] Download endpoint in control plane https://github.com/chainloop-dev/chainloop/pull/307
- [x] Update Helm Chart to support downloading https://github.com/chainloop-dev/chainloop/pull/310
```

**Comment by danlishka** [comment]
Related to #263
