### ISSUE TITLE
Prometheus integration

### ISSUE THREAD

**Issue by migmartri** [chainloop-dev/chainloop#458]
To be able to on-demand expose Prometheus metrics related to a given organization/workflow via a custom, protected metrics endpoint.
```[tasklist]
### Tasks
- [ ] https://github.com/chainloop-dev/chainloop/issues/1098
- [ ] https://github.com/chainloop-dev/chainloop/issues/1118
- [ ] https://github.com/chainloop-dev/chainloop/issues/1104
- [ ] https://github.com/chainloop-dev/chainloop/issues/1103
- [ ] https://github.com/chainloop-dev/chainloop/issues/1115
```
