### ISSUE TITLE
add authorization via casbin to API tokens

### ISSUE THREAD

**Issue by migmartri** [chainloop-dev/chainloop#466]
Currently, there is no authorization layer in Chainloop; since a user or API token is authenticated, it has access to most of the operations in its control organization.

This is especially problematic when we talk about API-tokens, which should be crafted with a limited purpose.

My proposal would be to take a look at https://casbin.org/ along with its [ent adapter](https://github.com/casbin/ent-adapter) and focus first on adding authorization to the API-tokens.

The reason to do it first with auth tokens is because in fact there are actions we do not want those tokens to be able to do, for example, we don't want them to add other tokens, we are avoiding this by checking that we are authentication via user

```go
        // This is a API operation that requires actual user to be logged in not API token
        // TODO: replace with authz layer, i.e casbin policies
        _, err = requireCurrentUser(ctx)
        if err != nil {
                return nil, err
        }
```

but this, instead, should be done by asking the casbin enforcer if we can do that operation instead.

```[tasklist]
### Tasks
- [x] Add casbin library + policy backend setup integrated with ent https://github.com/chainloop-dev/chainloop/pull/474
- [ ] Define a set of properties and limit scope of tokens to that, i.e workflow-contracts:create
- [ ] Add these policy definitions to database
- [ ] Start enforcing in each API call
```
