### ISSUE TITLE
Migrate documentation to the main Chainloop repository

### ISSUE THREAD

**Issue by danlishka** [chainloop-dev/chainloop#488]
Currently, we maintain our documentation in the separate [Chainloop Docs](https://github.com/chainloop-dev/docs) repository. 

By moving Chainloop docs to the main repository:
- We will simplify the process of updating documentation by integrating it with the new features' pull requests.
- We will encourage new contributions and indirectly improve the quality of our documentation. 

We already have [some docs](https://github.com/chainloop-dev/chainloop/blob/main/docs/integrations.md) in the main repo today.
```[tasklist]
### Tasks
- [x] add credentials
- [x] make the old deocs repo read only
- [x] merge code
- [x] make the deployment work again
- [x] update references in readme
- [x] update references raw.githubusercontent.com/chainloop-dev/docs
- [x] archive docs and update the README there
- [x] improve the deployment script
```
