### ISSUE TITLE
Design simple read/write roles for users in organization

### ISSUE THREAD

**Issue by migmartri** [chainloop-dev/chainloop#535]
We added an authorization backend that's currently configuring ACL for `apiTokens`, we want to add some basic authorization to users too. 

In this case though I am thinking that it might make more sense to look into roles as a first step. i.e `admin`, `writer`, `reader`.

This task is about evaluating if/what those roles could be, how they could be implemented with casbin and configured at the membership level. 
```[tasklist]
### Tasks
- [x] Add support for RBAC
- [x] Define viewer role and resource/action policies mapping
- [x] Load those policies into the policies DB
- [x] Define requests mapping
- [x] Apply authz checks in middleware
- [x] role management on membership invite
- [x] limit download permissions
- [x] expose role information in membership API
- [x] limit invitation mechanism
- [x] limit delete mechanism
```

**Comment by migmartri** [comment]
We are going to implement RBAC that will work alongside the current ACL setup used in the api-tokens 

![Image](https://github.com/chainloop-dev/chainloop/assets/24523/38f651f3-8810-408a-ba9c-c8be188e48de)

In practice, this means that user memberships will have associated roles, and for the first version, we are going to have only `admin` and `viewer` since the short-term goal is to have read-only users.

With regards to the resource/action/role mapping, we've a WIP document with the mapping which can be found [here](https://docs.google.com/document/d/1y_dAR40Zo3WSbYbusxrGWkiVDvweIpAZtx3gQofPM8U/edit?usp=sharing)

**Comment by migmartri** [comment]
We can define inheritance by using RBAC grouping policies, so for example

something like 

```go
// role: viewer can read and write workflow contracts
enforcer.AddPolicy("role:viewer", "workflow_contract", "list")
enforcer.AddPolicy("role:viewer", "workflow_contract", "read")
// role:editor can edit the contract
enforcer.AddPolicy("role:editor", "workflow_contract", "edit")
// We indicate that role:editor should inherit all the permissions from viewer
enforcer.AddGroupingPolicy("role:editor", "role:viewer")
// and finally assign the role editor to the user `deadbeef`
enforcer.AddGroupingPolicy("membership:deadbeef", "role:editor")
```

this ends up in the following policy table

```
 id  | ptype |         v0          |        v1         |  v2  | v3 | v4 | v5 
-----+-------+---------------------+-------------------+------+----+----+----
 155 | p     | role:viewer         | workflow_contract | list |    |    | 
 156 | p     | role:viewer         | workflow_contract | read |    |    | 
 157 | p     | role:editor         | workflow_contract | edit |    |    | 
 158 | g     | role:editor         | role:viewer       |      |    |    | 
 159 | g     | membership:deadbeef | role:editor       |      |    |    | 
```

and the implicit permissions for `deadbeef` are

```go
fmt.Println(enforcer.GetImplicitPermissionsForUser("membership:deadbeef"))
// => [[role:viewer workflow_contract list] [role:viewer workflow_contract read] [role:editor workflow_contract edit]] <nil>
```

and we can check permissions accordingly

```go
ok, err := enforcer.Enforce("membership:deadbeef", "workflow_contract", "list")
// ok => true
```
