### ISSUE TITLE
migrate to https://github.com/bufbuild/protovalidate

### ISSUE THREAD

**Issue by migmartri** [chainloop-dev/chainloop#603]
https://github.com/bufbuild/protovalidate seems to have replaced the library we are currently using github.com/envoyproxy/protoc-gen-validate 

This task is about migrating our current source code. 
```[tasklist]
### Tasks
- [x] configs https://github.com/chainloop-dev/chainloop/pull/667
- [x] crafter https://github.com/chainloop-dev/chainloop/pull/670
- [x] CAS API https://github.com/chainloop-dev/chainloop/pull/668
- [x] ControlPlane API https://github.com/chainloop-dev/chainloop/pull/673
- [x] middleware http https://github.com/chainloop-dev/chainloop/pull/673
```

**Comment by migmartri** [comment]
https://github.com/bufbuild/protovalidate/blob/main/docs/migrate.md
