### ISSUE TITLE
chore(controlplane) do not allow updating name for most resources

### ISSUE THREAD

**Issue by migmartri** [chainloop-dev/chainloop#680]
`names` are currently primed to become `identifiers` that the user could use for the interaction with the controlplane instead of `uuids`. 

We've already done most of the grunt work of setting such constraints i.e #663 #662, so next we should make sure `names` can not be updated.

This is something we've done already for contracts as part of this effort (note that this patch also includes updating by ID, which is out of the scope for now) https://github.com/chainloop-dev/chainloop/pull/674

The changes require

- update the ent schema to remove the setter on update
- update the `data` and `biz` layers to not to accept `name` anymore
- deprecate the protobuf property at the API layer

```[tasklist]
### Tasks
- [ ] https://github.com/chainloop-dev/chainloop/issues/683
- [ ] https://github.com/chainloop-dev/chainloop/issues/681
- [ ] https://github.com/chainloop-dev/chainloop/issues/682
- [ ] https://github.com/chainloop-dev/chainloop/issues/980
- [ ] review clients CLI
```
