### ISSUE TITLE
Update documentation on CycloneDX

### ISSUE THREAD

**Issue by javirln** [chainloop-dev/chainloop#837]
With the changes introduced on https://github.com/chainloop-dev/chainloop/releases/tag/v0.86.0 we added support for CycloneDX 1.6

The truth is that Chainloop supports not only CycloneDX SBOM files but also: HBOM, CBOM, SaasBOM and OBOM. We need to update Chainloop's documentation accordingly.
```[tasklist]
### Tasks
- [ ] Double check files mentioned on the description matches with the current implementation
- [ ] Update code base to incude the decided types to make it explicit Chainloop supports those types
- [ ] Update the documentation with the final list of types under CycloneDX
```
