### ISSUE TITLE
phase out robot accounts

### ISSUE THREAD

**Issue by migmartri** [chainloop-dev/chainloop#891]
[robot-accounts](https://docs.chainloop.dev/getting-started/workflow-definition#robot-account-creation) are being replaced by API tokens 

This means changes in the CLI workflow especially around attestation.

```[tasklist]
### Tasks
- [ ] https://github.com/chainloop-dev/chainloop/issues/889
- [x] Deprecate ra sub-command
- [ ] https://github.com/chainloop-dev/chainloop/issues/904
- [x] Add warning on authentication collision
- [ ] https://github.com/chainloop-dev/chainloop/issues/905
- [ ] make sure that lab attestation uses this key and the report works (digest link)
- [x] Remove robot-account information from doc overviews
- [ ] https://github.com/chainloop-dev/chainloop/issues/892
- [ ] https://github.com/chainloop-dev/chainloop/issues/893
```
